name: Build and Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist/angular_deploy/browser
          retention-days: 0

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4